dist: xenial
language: node_js
node_js:
  - '10'
before_install:
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt update
  - sudo apt install --install-recommends winehq-stable -y
install:
  - npm install
script: npm run build
